name: Run 1

on:
  schedule:
    - cron: "28,58 * * * *"
  workflow_dispatch:

jobs:
  run:
    name: "Run 1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Restore lastUpdatedValue cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: lastUpdatedValue
          key: last-updated-value-cache-1
      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Install dependencies
        run: dotnet restore
      - name: Run
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_1 }}
        run: dotnet run
      - name: Delete lastUpdatedValue cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete last-updated-value-cache-1 --confirm
      - name: Save lastUpdatedValue cache
        uses: actions/cache/save@v4
        with:
          path: lastUpdatedValue
          key: last-updated-value-cache-1
