name: Run

on:
  schedule:
    - cron: "28,58 * * * *"
  workflow_dispatch:

jobs:
  run:
    name: "Run 1"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Restore lastUpdatedValue
        uses: actions/cache@v4
        with:
          path: lastUpdatedValue
          key: last-updated-value-cache-1
      - name: Setup .NET SDK 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Install dependencies
        run: dotnet restore
      - name: Run
        run: dotnet run
      - name: Save lastUpdatedValue
        uses: actions/cache@v4
        with:
          path: lastUpdatedValue
          key: last-updated-value-cache-1
